In [8]:
import pandas as pd
import numpy as np

df_vendas = pd.read_csv("vendas_tech.csv")
df_gerentes = pd.read_excel("gerentes_lojas.xlsx")

/tmp/ipykernel_4947/841618403.py:4: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df_vendas = pd.read_csv("vendas_tech.csv")

### O comando display() mostra as 5 primeiras e 5 últimas linhas.

In [9]:
display(df_vendas)

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,2025-01-01
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,NaN
2,3,2023-02-25,NaN,"Monitor 27""",1200.0,1,Cliente_14859,NaN
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343,NaN
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,NaN
...,...,...,...,...,...,...,...,...
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755,NaN
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879,NaN
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160,NaN
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545,NaN
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274,NaN

### O comando head() mostra as 5 primeiras linhas, pode ser passado como parâmetro quantas linhas quer mostrar.

In [ ]:
df_vendas.head()
#df_vendas.head(15)

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,2025-01-01
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,NaN
2,3,2023-02-25,NaN,"Monitor 27""",1200.0,1,Cliente_14859,NaN
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343,NaN
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,NaN

### O comando tail() mostra as 5 últimas linhas, pode ser passado como parâmetro quantas linhas quer mostrar.

In [ ]:
df_vendas.tail()
#df_vendas.tail(15)

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755,NaN
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879,NaN
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160,NaN
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545,NaN
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274,NaN

### O comando sample() escolhe uma linha aleatória da tabela para mostrar, pode passar como parâmetro quantas linhas mostrar

In [ ]:
df_vendas.sample(5)

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
85364,85365,2023-07-10,Salvador,Notebook HP,3200.0,2,Cliente_27232,NaN
18713,18714,2023-05-20,Curitiba,Smartphone Samsung,2200.0,1,Cliente_10321,NaN
360,361,2023-05-03,RIO DE JANEIRO,iPhone 14,5500.0,1,Cliente_15164,NaN
38180,38181,2024-07-02,Curitiba,"Monitor 27""",1200.0,3,Cliente_28556,NaN
40037,40038,2023-10-20,Belo Horizonte,Notebook Dell,3500.0,1,Cliente_4990,NaN

### O comando .shape mostra a quantidade de linhas e colunas da tabela: (linhas, colunas)

In [ ]:
df_vendas.shape

(100100, 8)

### O comando .columns mostra o nome das colunas da tabela no formato de lista.

In [ ]:
df_vendas.columns

Index(['ID_Pedido', 'Data', 'Loja', 'Produto', 'Preco_Unitario', 'Qtd',
       'Cliente', 'Data_Base'],
      dtype='object')

### O comando info() mostra as informações da tabela.

In [ ]:
df_vendas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100100 entries, 0 to 100099
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   ID_Pedido       100100 non-null  int64
 1   Data            100100 non-null  object
 2   Loja            98099 non-null   object
 3   Produto         100100 non-null  object
 4   Preco_Unitario  100100 non-null  float64
 5   Qtd             100100 non-null  int64
 6   Cliente         100100 non-null  object
 7   Data_Base       1 non-null       object
dtypes: float64(1), int64(2), object(5)
memory usage: 6.1+ MB

### O comando describe() faz uma descrição estatística das colunas que possuem valores númericos.

In [ ]:
df_vendas.describe()

           ID_Pedido  Preco_Unitario            Qtd
count  100100.000000   100100.000000  100100.000000
mean    50004.810180     2000.204595       1.499101
std     28866.872543     1841.050733       1.241605
min         1.000000       40.000000       1.000000
25%     25008.750000      120.000000       1.000000
50%     50004.500000     1200.000000       1.000000
75%     75002.250000     3200.000000       1.000000
max    100000.000000     5500.000000      10.000000

## **Alguns comandos para fazer os tratamentos de dados.**

In [17]:
df_analise = df_vendas.drop(columns=["Data_Base"])
df_analise["Loja"] = df_analise['Loja'].fillna("Online")
df_analise['Data'] = pd.to_datetime(df_analise['Data'], format='%Y-%m-%d')

df_analise['Loja'] = df_analise['Loja'].str.strip()
df_analise['Loja'] = df_analise['Loja'].str.title()
df_analise

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750
2,3,2023-02-25,Online,"Monitor 27""",1200.0,1,Cliente_14859
3,4,2024-11-19,Rio De Janeiro,Mouse Gamer,120.0,2,Cliente_17343
4,5,2024-01-27,Rio De Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377
...,...,...,...,...,...,...,...
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274

## **Alguns comandos para criar novas colunas.**

In [23]:
df_analise['Faturamento'] = df_analise['Qtd'] * df_analise['Preco_Unitario']
df_analise['Forma_de_Venda'] = np.where(df_analise['Loja'] == 'Online', 'Online', 'Presencial')

display(df_analise['Loja'].unique())
dic_regioes = {
    'São Paulo': 'Sudeste',
    'Rio De Janeiro': 'Sudeste',
    'Belo Horizonte': 'Sudeste',
    'Online': 'Online',
    'Salvador': 'Nordeste',
    'Recife': 'Nordeste',
    'Curitiba': 'Sul',
    'Porto Alegre': 'Sul',
}
df_analise['Regiao'] = df_analise['Loja'].map(dic_regioes)
df_analise

array(['São Paulo', 'Belo Horizonte', 'Online', 'Rio De Janeiro',
       'Salvador', 'Recife', 'Curitiba', 'Porto Alegre'], dtype=object)

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Faturamento,Forma_de_Venda,Regiao
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,120.0,Presencial,Sudeste
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,5500.0,Presencial,Sudeste
2,3,2023-02-25,Online,"Monitor 27""",1200.0,1,Cliente_14859,1200.0,Online,Online
3,4,2024-11-19,Rio De Janeiro,Mouse Gamer,120.0,2,Cliente_17343,240.0,Presencial,Sudeste
4,5,2024-01-27,Rio De Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,2200.0,Presencial,Sudeste
...,...,...,...,...,...,...,...,...,...,...
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755,5500.0,Presencial,Sul
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879,7000.0,Presencial,Sul
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160,4400.0,Presencial,Sudeste
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545,11000.0,Presencial,Nordeste
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274,6400.0,Presencial,Sudeste